### ISSUE TITLE
Parsing img tags in md [ERROR with src]

### ISSUE THREAD

**Issue by AdityaPrasad275** [zerodevx/zero-md#101]
I was parsing [this](https://github.com/AdityaPrasad275/Leetcode_DSA/blob/main/Linked%20Lists/Copy%20List%20with%20random%20pointer.md) md file which happens to be in Linked List folder (which itself is in root). Now when making that md, here's the tag i used 
  `<image src="./images/deepcopy.png">` (I tried to correct this in my latest commit so you might not see it)  
So the src makes sense for this md file. Like when this md renders, the image renders. But when I am parsing this file in an html file ([this](https://github.com/AdityaPrasad275/Leetcode_DSA/blob/website/website.html)) which happens to be in root folder, the src for the image tag in processed html stays same, so now `"./images/deepcopy.png"` refers to a folder `images` in root folder (which doesn't exist) and hence the image is not rendered. 

I tried to fix it by changing the src to "./Linked Lists/images/deepcopy.png" and it works in that the image displays correctly on the website but the .md file doesn't render it (if you were to open it on github) because for it the src becomes incorrect.

So please try to change the src of tags accordingly too if possible in <zero-md>.

**Comment by zerodevx** [comment]
Relative URLs are prefixed with the base url (in line with `src`) so if images work in your MD file, they should similarly work in HTML. Try again with [V3](https://github.com/zerodevx/zero-md/releases/tag/v3.0.0) and see if it works. 

Closing for now, feel free to reopen.
