### ISSUE TITLE
zero-md-copy to clipboard

### ISSUE THREAD

**Issue by mohdniyazkhan** [zerodevx/zero-md#110]
I want to override the copy-to-clipboard functionality provided by zero-md with my custom code can I do that?
I am rendering everything inside <zero-md>

**Comment by zerodevx** [comment]
`zero-md` doesn't ship with copy-to-clipboard feature.

**Comment by zerodevx** [comment]
You can however add your own using a snippet like so:

https://github.com/zerodevx/zero-md/blob/d70aa3b1a329acef2bf266c335de20888421abbd/docs/index.html#L12-L50

Closing for now.
