### ISSUE TITLE
v3 Question: Is there an easy way to force the theme to be light or dark?

### ISSUE THREAD

**Issue by jdcoldsmith** [zerodevx/zero-md#111]
Maybe I am missing something, but I would like to have the option to force the theme of the `zero-md` element to either be light or dark. I was originally thinking it would be an attribute you can set on the element, something like `force-theme="light"` but it appears that isn't an option.

Thank you for your help!

**Comment by zerodevx** [comment]
Right now it's manual. This overrides the defaults to load `light` styles only:

```html
<head>
  ...
  <script type="module">
    import ZeroMd from 'https://cdn.jsdelivr.net/npm/zero-md@3'
    customElements.define('zero-md', class extends ZeroMd {
      async load() {
        this.template = `
<style>:host { display: block; position: relative; contain: content; } :host([hidden]) { display: none; }</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/github-markdown-css@5/github-markdown-light.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@highlightjs/cdn-assets@11/styles/github.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css" />
`
      }
    )
  </script>
</head>
<body>
  <zero-md src="example.md" />
</body>
```

**Comment by jdcoldsmith** [comment]
Gotcha, that makes sense! Thank you very much for your prompt response!

**Comment by zerodevx** [comment]
Just a note to make sure you `await super.load()` (I forgot).

**Comment by tannerstern** [comment]
Hey @zerodevx am I correct in thinking that with v3.1.0 and up, the best way to do this is with the styles presets?
```
this.template = STYLES.preset('light')
```

**Comment by zerodevx** [comment]
> Hey @zerodevx am I correct in thinking that with v3.1.0 and up, the best way to do this is with the styles presets?

Yes that's right. Both ways work - but the styles preset composes the template in a one-liner, for convenience.
