### ISSUE TITLE
`Front Matter` on zero-md is it possible 

### ISSUE THREAD

**Issue by KSDeshappriya** [zerodevx/zero-md#114]
can I use like as
---
title: TITLE
date: YYYY-MM-DD HH:MM:SS +/-TTTT
categories: [TOP_CATEGORIE, SUB_CATEGORIE]
tags: [TAG]     # TAG names should always be lowercase
---

**Comment by zerodevx** [comment]
I don't think so - check out Jekyll (https://jekyllrb.com/) instead.
