### ISSUE TITLE
Sometimes when there is a $ in the markdown text, the html is not rendered properly

### ISSUE THREAD

**Issue by NewGHUser4321** [zerodevx/zero-md#127]
Sometimes when there is a $ in the markdown text, the html is not rendered properly. 
Eg markdown:
```
The amount for **ABC Inc.** is $658,002.00. The total revenue amount is $18,825,415.25. The revenue used is -$44,659,856.25, indicating that the expense amount has significantly exceeded the budget.
```
The outcome is like this
![image](https://github.com/user-attachments/assets/b026d85a-7185-42dc-9367-ef9048d3197f)
Looks like $ is causing the issue but, as you can see in the last statement it doesn't.

I tried both external markdown and inline markdown. Both results the same.

**Comment by zerodevx** [comment]
`katex` is recognising this as a math expression. Try loading `zero-md` like so:

```html
<head>
  <script type="module">
    import ZeroMd from 'https://cdn.jsdelivr.net/npm/zero-md@3'
    customElements.define('zero-md', class extends ZeroMd {
      async load() {
        await super.load({
          katexOptions: {
            nonStandard: false
          }
        })
      }
    })
  </script>
</head>
```

Here's the repro: https://plnkr.co/edit/pnuvo1hWZ5pUgTkO

**Comment by NewGHUser4321** [comment]
This fixes it. Thank you.
