### ISSUE TITLE
Dark Mode gives unreadable black text on black background in markdown grids

### ISSUE THREAD

**Issue by BrendanTWhite** [zerodevx/zero-md#130]
I've got a super-simple grid in markdown:

```markdown
| ID         | Text |
| ---------- | ---- |
| 01         | Foo  |
| 02         | Bar  |
```

... and a super-simple HTML file to display it:

```html
<head>
  <script type="module" src="https://cdn.jsdelivr.net/npm/zero-md@3?register"></script>
</head>
<body>
  <zero-md src="grid.md"></zero-md>
</body>
```
... and when I view it in light mode it's gorgeous...

<img width="686" alt="light" src="https://github.com/user-attachments/assets/3bd4e574-1020-4e8a-9e3e-a217ac76889c" /> 

...but when I view it in dark mode it's unreadable.

<img width="686" alt="dark" src="https://github.com/user-attachments/assets/64056b36-0147-4d93-815c-f81ef4c19c0d" />

These files can be seen at [thespia.com/zero-md](https://thespia.com/zero-md/) if that's helpful. I've reproduced this in Safari and Edge.

**Comment by zerodevx** [comment]
Not valid HTML - try changing your `.html` to:

```html
<!doctype html>
<html lang="en">
  <head>
    <script type="module" src="https://cdn.jsdelivr.net/npm/zero-md@3?register"></script>
  </head>
  <body>
    <zero-md src="grid.md"></zero-md>
  </body>
</html>
```

**Comment by BrendanTWhite** [comment]
Well ... that's embarrassing! Thanks @zerodevx, you are of course correct. I'll close this issue.

**Comment by zerodevx** [comment]
Happy to help!
