### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by israelfloresdga** [zerodevx/zero-md#18]
I'm using the development server of LitElement, you have any idea`what can I do to resolve this `Reason: CORS header 'Access-Control-Allow-Origin' missing`

html
```html
<zero-md id="zero-viewer" manual-render="" src="https://gitlab.com/israelfloresdga/temp/raw/master/0.md"></zero-md>
```

Console
` [zero-md] Error getting file https://gitlab.com/israelfloresdga/temp/raw/master/0.md zero-md.js:75:19
`

**Comment by zerodevx** [comment]
Unfortunately this is a Content Security Policy issue so there's nothing I can do on my end... You should either host the markdown file from the same domain as your development server, or the Gitlab server needs to add an `Access-Control-Allow-Origin:*` header in response to your HTTP request to `https://gitlab.com/israelfloresdga/temp/raw/master/0.md`.

Alternatively, push your `0.md` file into a Github repo instead and access the raw file by for eg `https://raw.githubusercontent.com/israelfloresdga/temp/master/0.md`. Github automatically adds the Access-Control-Allow-Origin:*` header so it should work.

Here are some resources regarding CORS: 

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

**Comment by israelfloresdga** [comment]
Thanks

**Comment by ManPython** [comment]
And this same case is with local? Eg. file:/// ..test.html where is this all? Or can be resolved. 
It's base if only local// as running server
