### ISSUE TITLE
Make es modules compatible

### ISSUE THREAD

**Issue by lastmjs** [zerodevx/zero-md#25]
Hey,

I would like to be able to import the element as an es module, but there is no module property in the package.json, and the element seems generally not setup for es modules

**Comment by zerodevx** [comment]
Yes, the property values are pointed wrong. Historically, this repo was created at the time when web components were a new spec (v0) and only just somewhat implemented in Chrome, and where `Polymer` was the framework Google created to introduce custom elements for general consumption. Lots of legacy workflows are now deprecated, but remnants of them still exist here.

This repo is due for a major update - hopefully by then legacy stuff should be cleaned up, and support for modern ES module consumption added.

**Comment by zerodevx** [comment]
V2 is released - with old stuff cleaned up (good riddance to `HTMLImports`!), and should be in spec with modern standards. So you can:

```bash
$ npm i -D zero-md
```

Then you can:

```js
import ZeroMd from 'zero-md'

customElements.define('zero-md', ZeroMd)

render(`<zero-md src=${src}></zero-md>`)
```

Please refer to the related section here: https://zerodevx.github.io/zero-md/installation/

Closing this (finally) for now! 🎉  Feel free to re-open is something's wrong!
