### ISSUE TITLE
Automatic re-render

### ISSUE THREAD

**Issue by lastmjs** [zerodevx/zero-md#26]
"Note that if changes are made to <zero-md> attributes or <template> children dynamically, call the render() method on that instance to force a re-render."

This leads to not very ideal code for triggering updates to my markdown. I was a render React-like render function with lit-html, and to get zero-md to update I have to set a timeout and imperatively call render on the zero-md instance, which doesn't fit with the flow of everything.

Could you expose a property that I could bind to, which would let me set the markdown text and then automatically re-render? I'm happy to PR if you'll accept

**Comment by zerodevx** [comment]
Hi, thanks for your note. `zero-md` is due for a major update and this one of the features I plan to add in the new release.

Will love to accept PRs in the meantime.

**Comment by zerodevx** [comment]
V2 is released and now changes to `src` attribute will automatically trigger a re-render.

There are quite some other changes too, more can be found in the docs: https://zerodevx.github.io/zero-md/

Closing this for now... but feel free to re-open if something's wrong!
