### ISSUE TITLE
Not rendering on Microsoft Edge clients.

### ISSUE THREAD

**Issue by benrobson** [zerodevx/zero-md#30]
https://gyazo.com/e877c1153eb686cbf8ba84bc5682d4d1

**Comment by zerodevx** [comment]
1. Does this happen only on Edge?

2. Could you post your code, and also console logs?

Thanks.

**Comment by benrobson** [comment]
> 
> 
>     1. Does this happen only on Edge?
> 
>     2. Could you post your code, and also console logs?
> 
> 
> Thanks.

Mozilla Firefox: https://gyazo.com/8d37a73533a4e9b9e29e816f55ab13ac
Microsoft Edge: https://gyazo.com/2ad9e7fd1a2e6b9e21828cf457ef4d40

Code: https://hastebin.com/zanocexogu.xml
The console doesn't actually produce anything, no errors.

**Comment by zerodevx** [comment]
Can you show what's in your document `<head>`? Also, if you visit https://zerodevx.github.io/zero-md/ in Edge, does the page render?

**Comment by benrobson** [comment]
Visiting https://zerodevx.github.io/zero-md/ give me this: https://gyazo.com/8f455de869fc08f84d309292d996c619
<head> code: https://hastebin.com/kowevofiwo.xml

**Comment by benrobson** [comment]
Hey just checking in, any progress on this?

**Comment by zerodevx** [comment]
Hey - are you supporting super old versions of Edge? The new Edges are Chromium based and I don't expect to have issues with them. I just tested on Edge v84 and it seems ok... =/

What's your Edge version?

**Comment by benrobson** [comment]
I'm using:
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

**Comment by zerodevx** [comment]
IE11 is already phased out... What you're on is the non-chromium Edge, which will be phased out by early next year I believe.

The underlying tech is [web components](https://developer.mozilla.org/en-US/docs/Web/Web_Components), so for older browsers like IE11 and non-chromium Edge, the required APIs are polyfilled by [webcomponentsjs](https://github.com/webcomponents/webcomponentsjs), an open-source project led by Google.

My best guess is there's a regression in `webcomponentsjs`. Perhaps you can try again by tying `webcomponentsjs` to an older version:

```html
<head>
  <script src="https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@2.2.10/webcomponents-loader.min.js"></script>
  <script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@1/src/zero-md.min.js"></script>
  ...
</head>
```

**Comment by benrobson** [comment]
Added the new head lines and still no md
![image](https://user-images.githubusercontent.com/15405528/90607456-92657e80-e244-11ea-9d59-20fca5c6ef64.png)

**Comment by zerodevx** [comment]
Not sure what's going on too - and I don't currently have an Edge v44 to test. 

1. Is your page published online? 

2. Are there any console logs? 

3. In the devtools `Network` tab, do you see requests to `zero-md.js`, `marked.js` and `prism.js`? 

4. In the devtools `Elements` tab, if you expand `zero-md` element, do you see something like `#shadow-root`?

**Comment by benrobson** [comment]
Since the new Windows release is removing IE and replacing with chromium edge this is invalid.

**Comment by zerodevx** [comment]
Hi, FWIW, V2 is out with a **legacy** build that (hopefully) works for IE11-era browsers. 

The HTML looks like:

```html
<head>
  <!-- Lightweight client-side loader that feature-detects and load polyfills only when necessary -->
  <script src="https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@2/webcomponents-loader.min.js"></script>
  <!-- Load the legacy (transpiled) build of <zero-md> -->
  <script defer src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@2/dist/zero-md.legacy.min.js"></script>
</head>
```

More info here: https://zerodevx.github.io/zero-md/advanced-usage/
