### ISSUE TITLE
Catch errors/warnings

### ISSUE THREAD

**Issue by ThaumicTom** [zerodevx/zero-md#31]
If zero-md throws a 404 warning, I'd like to catch the error, so I can display a custom 404 page + cancel the process. Is that possible?

**Comment by zerodevx** [comment]
At the moment there's no baked-in mechanism in `zero-md` to handle errors. That said, given your use-case I believe it's possible through javascript outside `zero-md` i.e. manually check via `XMLHttpRequest` if the file exists; and display your error message if it doesn't.

**Comment by zerodevx** [comment]
V2 is released and provides some basic support for download errors.

Read more about the `zero-md-error` custom event here: https://zerodevx.github.io/zero-md/attributes-and-helpers/

Closing this for now; feel free to re-open is something's wrong! 🎉
