### ISSUE TITLE
Google Translate cannot handle MD file

### ISSUE THREAD

**Issue by decryp2kanon** [zerodevx/zero-md#32]
HTML is translated well, but MD file won't be translatable. How can I enable this translation feature?

1. Google translate cannot handle MD file
2. Popup translation neither working on Chrome browser

HTML
https://github.com/decryp2kanon/test_website/blob/a1ad8aaf95488632e276bcbfeb3808999cc25bd1/index.html#L131

MD
https://github.com/decryp2kanon/test_website/blob/master/README.md

Screenshot on your website
![image](https://user-images.githubusercontent.com/60179867/87359543-002bd580-c536-11ea-8f0c-cb275cc90458.png)

Many thanks,
kanon

**Comment by zerodevx** [comment]
Yikes. Thanks for raising this. My guess is Google Translate doesn't access the shadow DOM. Have you tried `no-shadow`?

```html
<zero-md no-shadow src="..."></zero-md>
```

**Comment by decryp2kanon** [comment]
> <zero-md no-shadow src="..."></zero-md>

Fantastic! It seems works :+1: Do you think this workaround has any side effect? Anyway thank you so much!

**Comment by zerodevx** [comment]
Hi! Glad it works now. Your site looks good!

Re side-effects, the biggest difference is CSS encapsulation. Using `no-shadow`, there is the possibility that styles from outside (i.e. your document-level styles) may bleed into the markdown body; and vice-versa. Your site doesn't look like it's affected though.

**Comment by decryp2kanon** [comment]
Thanks so much! Now I can close this issue 😊
