### ISSUE TITLE
Is it possible to use your zero-md with mathjax?

### ISSUE THREAD

**Issue by PanPeople** [zerodevx/zero-md#35]
Hi, is it possible to use your zero-md with mathjax?

**Comment by zerodevx** [comment]
Hi, do you have an example or a reproduction of what you wish to do?

**Comment by PanPeople** [comment]
Hmmm... example would be fine.
But here how i want to make it:

my-markdown.md looks like that: 
##Hello World
$a_2 + b^2 = d^e $


part of my site:
<zero-md src="https://www.example.com/my-markdown.md"></zero-md>

How it looks:
No conversion at all even if i add special settings to math_jax script part which allow me to use $ $

**Comment by zerodevx** [comment]
So.. say you have a markdown file:

`my-markdown.md`:

```markdown
## Hello World

$a_2 + b^2 = d^e $
```

and you have a HTML file:

`index.html`:

```html
<head>
  <!-- Configure your MathJax settings here -->
  <script>
    MathJax = {
      tex: {
        inlineMath: [ ['$', '$'], ['\\(', '\\)'], ],
      },
    };
  </script>

  <!-- Load `zero-md` -->
  <script async src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@1/src/zero-md.min.js"></script>
</head>
<body>
  <!-- Add the `no-shadow` attribute -->
  <zero-md id="md" src="my-markdown.md" no-shadow></zero-md>

  <!-- Load the MathJax library AFTER markdown is rendered -->
  <script>
    md.addEventListener('zero-md-rendered', () => {
      let el = document.createElement('script');
      el.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js';
      document.head.appendChild(el);
    });
  </script>
</body>
```

Here's the working example: https://plnkr.co/edit/SdzWj39SOVpntGTn?open=lib%2Fscript.js

**Comment by PanPeople** [comment]
Thank you very much
