### ISSUE TITLE
Rendered content is inside a scrolling area

### ISSUE THREAD

**Issue by volkanunsal** [zerodevx/zero-md#38]
I'm noticing a strange bug in the rendered document. The rendered content is cut off and contained by a scrollable area, but I don't see anything that would contain it and there aren't any DOM elements that have an overflow rule. The content is rendered without a shadowDom, which makes this all the more strange.

<img width="1107" alt="Screen Shot 2020-10-14 at 8 51 42 AM" src="https://user-images.githubusercontent.com/151600/95991376-b1266280-0dfa-11eb-97f2-6620391e3a95.png">

[Here is a script to reproduce it.](https://gist.githubusercontent.com/volkanunsal/d7c94f9090f01fee890952ecde3686dd/raw/b9ea6becdb94d2a5442c6ba9e062c4b3b9c2bb30/scroll-bug.js)

**Comment by zerodevx** [comment]
Not sure if it's a bug though. It seems the document is not in proper markdown format. 4 spaces in markdown is interpreted as a code block - which actually is the scrollable area you see. This document seems more suited to be wrapped using the in-built HTML `<pre>` tag instead.

**Comment by volkanunsal** [comment]
Here is better screenshot. I think it might actually be related to puppeteer. I don't see this issue if I load the file from a local html file. 

<img width="1242" alt="Screen Shot 2020-10-14 at 9 29 41 AM" src="https://user-images.githubusercontent.com/151600/95996002-2a748400-0e00-11eb-9d92-1fdfd039ee66.png">

**Comment by zerodevx** [comment]
Ah ok. This was the section I was referring to:

![image](https://user-images.githubusercontent.com/9677698/95998120-1d3eb000-0e67-11eb-8a25-596236cc1036.png)

It's rendered as a `<code>` block but (based on the source document) it's expected behaviour - because of the 4 spaces rule =/
