### ISSUE TITLE
Getting a CORS error locally

### ISSUE THREAD

**Issue by officeSpacePirate** [zerodevx/zero-md#41]
To try your code out, I created a basic index.html:
```
<!doctype html>
<html lang="en">

<head>
    <title>Try This</title>
    <meta charset="utf-8">
    <script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@2/dist/zero-md.min.js"></script>
</head>

<body>
    <zero-md src="README.md"></zero-md>
</body>

</html>
```

README.md:
```
# This is a markdown file

This is text

## This is an h2

* This
* Is
* A
* List

```

When I open the file locally, I get this CORS error:
`Fetch API cannot load file:///C:/{local path to}/README.md. URL scheme must be "http" or "https" for CORS request.`

I don't have this issue with other static pages that use js locally, so I'm not sure what your stuff is doing to trigger CORS; is there anything that can be done? I'm looking for the lightest weight solution to render static documentation and this would be great if I don't have to push it somewhere to view changes.

**Comment by zerodevx** [comment]
Browsers don't allow access of local files - if they do, then anyone will be able to read your hard disk contents. If you want to open locally, your `index.html` and your `README.md` need to be hosted using a local web server.
