### ISSUE TITLE
Automatically re-render when src changes?

### ISSUE THREAD

**Issue by mvalente** [zerodevx/zero-md#42]
Any clue or tips on how to get this to work?

Currently setting the "src" attribute in the "zero-md" element using javascript but I'm not getting auto re-render.

        <zero-md id="mymd" src="INDEX.md"></zero-md>

        <button onclick="myFunction()">Try it</button>

        <script>
        function myFunction() {
          document.getElementById("mymd").src = "1993-05-15-off-to-download-linux.md";
        }
        </script>

**Comment by zerodevx** [comment]
It should work - here's a repro: https://plnkr.co/edit/6YZRNp2ekGeHfLcT?open=lib%2Fscript.js&preview

What is your use-case like, and how is `myFunction()` being called?

**Comment by mvalente** [comment]
Thanks for the hint. My bad, I was requesting v1 from jsdeliver.net..... I blame Copy/Paste :-) Using your example and requesting V2 makes it work.

myFunction is called when I click the "Try It" button although its an intermediate test for my actual use case: I have a INDEX.md file being used in index.html through zeromd component src attribute. This file has a list of links (which translates in the shadow-dom in a list of A elements) and when the user clicks one of those links (point to a local XXX.md file) the zeromd element is updated by replacing its src element.

This avoids creating an html file for each XXX.md file, I want to reuse the zeromd component for all the XXX.md files by replace the src element with the href of the link that was clicked.

Is there a better way to do this? Right now I'm adding an onclick event on each A element.

**Comment by zerodevx** [comment]
> Thanks for the hint. My bad, I was requesting v1 from jsdeliver.net..... I blame Copy/Paste :-) Using your example and requesting V2 makes it work.

Ah yes, automatic re-render is a V2 feature that's not in V1.

> myFunction is called when I click the "Try It" button although its an intermediate test for my actual use case: I have a INDEX.md file being used in index.html through zeromd component src attribute. This file has a list of links (which translates in the shadow-dom in a list of A elements) and when the user clicks one of those links (point to a local XXX.md file) the zeromd element is updated by replacing its src element.
> 
> This avoids creating an html file for each XXX.md file, I want to reuse the zeromd component for all the XXX.md files by replace the src element with the href of the link that was clicked.

Yes that can be done!

> Is there a better way to do this? Right now I'm adding an onclick event on each A element.

I think your implementation is probably the correct way to do this. 👍

**Comment by zerodevx** [comment]
This issue is a feature of `v2` so marking this as resolved.
