### ISSUE TITLE
No Support for React-Native

### ISSUE THREAD

**Issue by kethan1** [zerodevx/zero-md#43]
I am using React-Native with Expo. When I install this package with `yarn`, and I try to use it, I get this error: `Can't Find Variable HTMLElement`.

**Comment by zerodevx** [comment]
Yup unfortunately there's no support - `zero-md` is intended for web use. The problem with React Native is that it removes all the DOM-related stuff and replaces them with native code, so the UI-component semantics are different. =/

It should work with just React though.

**Comment by kethan1** [comment]
Okay, sure, will close issue :)
