### ISSUE TITLE
boilerplate html → doesn't load content

### ISSUE THREAD

**Issue by filipaldi** [zerodevx/zero-md#44]
I've tried your boilerplate HTML and it doesn't load any content. What I am missing?

I've copied the following code and included my own MD files.
The result → nothing is rendered in a browser.

```html
<head>
  <!-- Import element definition -->
  <script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@2/dist/zero-md.min.js"></script>
  ...
</head>
<body>
  ...
  <!-- Profit! -->
  <zero-md src="/example.md"></zero-md>
  ...
</body>
```

**Comment by zerodevx** [comment]
Are there any messages shown in console? Also, could you paste your HTML file in its entirety here?

**Comment by filipaldi** [comment]
Console messages:
![Screenshot 2020-12-12 at 12 05 04](https://user-images.githubusercontent.com/75883012/101982219-904f8180-3c72-11eb-8e08-634ebf4cf7d3.png)

exactly the code
```
<html>
<head>	
	<!-- Import element definition -->
	<script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@2/dist/zero-md.min.js"></script>	
	
</head>
<body>
	<zero-md src="../testing.md"></zero-md>
</body>
</html>
```

**Comment by zerodevx** [comment]
Your markdown file needs to be hosted. I guess you opened the HTML file by double-clicking on it. Browsers don't allow javascript to access files on the local hard drive because security.

If you have NodeJS installed on your machine, you can run something like:

```
npx http-server
```

then point to `http://localhost:8080` on your web browser.

**Comment by boehs** [comment]
Please don't close, this is very helpful

**Comment by zerodevx** [comment]
This has been added as a note in the project docs homepage: https://zerodevx.github.io/zero-md/

Hope this helps!
