### ISSUE TITLE
Prism loading issue

### ISSUE THREAD

**Issue by jonmann20** [zerodevx/zero-md#54]
Getting some issues with loading Prism.

`window.Prism is undefined`
and
`Cannot read property 'highlightAllUnder' of undefined`

The script is added to document.head and loaded, but may be some race condition.

Also would be great in general to have this be a local file as I currently have to allow all of cdn.jsdelivr.net for this.

**Comment by zerodevx** [comment]
Could you paste the HTML code you're using?

**Comment by jonmann20** [comment]
```js
import 'zero-md';
class Foo extends LitElement {
  static properties = {item: {type: Object}};

  render() {
    return html`
        ${this.item?.changelog && this.item.changelog !== '' ? html`
            <zero-md @zero-md-rendered="${() => this.dispatchEvent(new Event('notifyResize'))}">
                <script type="text/markdown">${this.item.changelog}</script>
            </zero-md>
        ` : ''}
    `;
  }
}
```

**Comment by zerodevx** [comment]
> The script is added to document.head and loaded, but may be some race condition.

What is being added into `<head>`? 

> Also would be great in general to have this be a local file as I currently have to allow all of cdn.jsdelivr.net for this.

It's possible to load dependencies locally. If you can give more details about your code and setup maybe I can help.

Lastly, you should probably import the `<zero-md>` class, then define the `customElement`:

```js
import ZeroMd from 'zero-md'

customeElements.define('zero-md', ZeroMd)

class Foo extends LitElement {
  ...
}
```

**Comment by jonmann20** [comment]
```html
<script src="https://cdn.jsdelivr.net/gh/PrismJS/prism@1/prism.min.js" data-manual=""></script>
<script src="https://cdn.jsdelivr.net/gh/PrismJS/prism@1/plugins/autoloader/prism-autoloader.min.js"></script>
```
are added to head.

I'm using rollup/nodeResolve to bundle for production.  Just imports (w/nodeResolve server) for dev.

I'm using the component in multiple places in the application so that would result in a duplicate registry error.

**Comment by jonmann20** [comment]
Also seeing double rendering (maybe) related to this.   Calling `.refreshContent()` prints this error.

**Comment by jonmann20** [comment]
FYI, rolling back to v2.1.1 fixed the double rendering issue so that is likely something separate from Prism.

**Comment by zerodevx** [comment]
Thanks for investigating. I think some of the `v2.2.0` code re dynamic content refresh needs to be refactored. I'll get to clearing this backlog soon. 🙏  

Will keep you updated in this thread.

**Comment by zerodevx** [comment]
Hi, FYI there's a new `v2.3.0` release - are you still encountering issues with this?

**Comment by jonmann20** [comment]
Thanks, yes this seems to have resolved the double loading issue.  I will close this for now and keep an eye out for the previously mentioned prism issue.
