### ISSUE TITLE
Render `.md` file inside `.mdx` file

### ISSUE THREAD

**Issue by iamrajiv** [zerodevx/zero-md#55]
I want to render the `.md` file inside `.mdx` file. I did this

```mdx
import ZeroMd from "zero-md";

customElements.define('zero-md', ZeroMd)

app.render(<zero-md src="https://raw.githubusercontent.com/wechaty/openapi/main/CHANGELOG.md"></zero-md>, target)
```

But it's not rendering.

**Comment by zerodevx** [comment]
Which framework are you using?

For one, it feels like in your render call:

```js
app.render(<zero-md src="https://raw.githubusercontent.com/wechaty/openapi/main/CHANGELOG.md"></zero-md>, target)
```
the first param should be quoted:

```js
app.render(`<zero-md src="https://raw.githubusercontent.com/wechaty/openapi/main/CHANGELOG.md"></zero-md>`, target)
```

Also, `https://raw.githubusercontent.com/wechaty/openapi/main/CHANGELOG.md` returns a `404`.

**Comment by iamrajiv** [comment]
I am using Docusaurus. Can you check this PR https://github.com/wechaty/wechaty.js.org/pull/924, please?

**Comment by zerodevx** [comment]
I'm not sure what's going on. AFAICT, if you're using [`mdxjs`](https://github.com/mdx-js/mdx) to handle markdown transformation, then you probably don't need `<zero-md>`?

**Comment by antonym** [comment]
@zerodevx I'm trying to do the same thing using latest Docusaurus.  It will render in yarn start but when I try and yarn build, I get the following error.
```
yarn run v1.22.10
$ docusaurus build

[en] Creating an optimized production build...

✔ Client
✖ Server
  Compiled with some errors in 5.55s

Docusaurus Node/SSR could not render static page with path=/docs/changelog because of error: HTMLElement is not defined

ReferenceError: HTMLElement is not defined
error building locale=en
Error: Failed to compile with errors.
    at .../node_modules/@docusaurus/core/lib/webpack/utils.js:202:24
    at .../node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (.../node_modules/webpack/lib/MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
The change log being docs/changelog.mdx
```
---
id: changelog
title: Changelog
description: changelog
hide_table_of_contents: true
---
import ZeroMd from 'zero-md'

<zero-md src='https://url-to-changelog.com/CHANGELOG.md'></zero-md>

**Comment by zerodevx** [comment]
@antonym There should be a way to exclude `zero-md` from SSR. The component should be rendered client-side, not pre-rendered server-side.
