### ISSUE TITLE
Image not rendering

### ISSUE THREAD

**Issue by crypt0inf0** [zerodevx/zero-md#57]
Why image are not rendering?
```
<center>

![](https://i.imgur.com/aUpWefG.png)</center>
```
I tried without `<center>` Nothing works.

**Comment by zerodevx** [comment]
Are there any error messages in the browser console?

**Comment by crypt0inf0** [comment]
I got `i.imgur.com/aUpWefG.png:1 GET https://i.imgur.com/aUpWefG.png 403` error but visiting the image url on the browser works fine.

**Comment by zerodevx** [comment]
So imgur doesn't support hotlinking. Try Googling "use github issues to store image" to generate the image URL instead.

**Comment by crypt0inf0** [comment]
Hosting the image on github works fine.
