### ISSUE TITLE
Custom css style

### ISSUE THREAD

**Issue by crypt0inf0** [zerodevx/zero-md#58]
Does anyone have custom style with `code`, `syntax` same as github? ie. same `code` background color, `syntax` color, etc... as github

**Comment by zerodevx** [comment]
[V3](https://github.com/zerodevx/zero-md/releases/tag/v3.0.0) uses [highlightjs](https://github.com/highlightjs/highlight.js) for syntax highlighting now and comes built-in with a similar code theme as Github - do check it out.
