### ISSUE TITLE
errors when there are hashes in url

### ISSUE THREAD

**Issue by zaszlo** [zerodevx/zero-md#6]
Hello,

I have components in the page that are called using hashes (those id/anchors are not inside md), the page loads but I get these errors, my console is bloated with them:
```
Uncaught DOMException: Failed to execute 'querySelector' on 'DocumentFragment': '#1' is not a valid selector.
at HTMLElement._scrollTo (https://cdn.rawgit.com/zerodevx/zero-md/v1.1.0/build/zero-md.html:1:4077)
    at window.setTimeout (https://cdn.rawgit.com/zerodevx/zero-md/v1.1.0/build/zero-md.html:1:967)

_scrollTo | @ | zero-md.html:1
-- | -- | --
  | window.setTimeout | @ | zero-md.html:1
  | setTimeout (async) |   |  
  | a | @ | zero-md.html:1
  | _fire | @ | zero-md.html:1
  | Promise.all.then | @ | zero-md.html:1
  | Promise.then (async) |   |  
  | render | @ | zero-md.html:1
  | connectedCallback | @ | zero-md.html:1
  | append | @ | swiper.js:634
  | loopCreate | @ | swiper.js:2255
  | h.init | @ | swiper.js:3961
  | h | @ | swiper.js:3854
  | (anonymous) | @ | (index):187
```

Is there a way to fix it?

**Comment by zerodevx** [comment]
Hello, I definitely need more details, like: 

1. Browser and version;
2. What other components are loaded;
3. What's the URL structure?

Is it possible to do a quick repro on jsbin so I can take a look?

Thanks.

**Comment by zaszlo** [comment]
Chrome is automatically updating to newest version, [swiper](https://idangero.us/swiper/api/) with the option `hashNavigation: true`, jquery and for zero-md also the [webcomponents loader](https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.1.0/webcomponents-loader.js).

It would take me a while to prepare a repo, but I think any demo from swiper with that option so to have a hash in the url from start would trigger this problem. Not sure maybe also without swiper just a simple js to start out with a hash redirect present on the page, but not inside the md.

**Comment by zaszlo** [comment]
[here's a zip with my html, etc. structure.](https://drive.google.com/file/d/1t4rPnu9BtV9iKjb4f3vE1BtteD9zza9C/view?usp=sharing)

**Comment by zerodevx** [comment]
Oh that's because the numeric hash value is not a valid CSS selector, so `<zero-md>`'s anchor link feature throws an exception. Functionality is not affected though so everything still works.

As a quick workaround, trying renaming all your swiper slides' `data-hash` value to something like `slide1` etc.

```html
...
<div class="swiper-slide" data-hash="slide1">
...
</div>
<div class="swiper-slide" data-hash="slide2">
...
</div>
...
```

I'll fix this in the next release which should land very soon. There are some changes to how web components should be loaded as well - basically the community has decided that `HTMLImports` be deprecated in favour of `ES Modules`.

**Comment by zaszlo** [comment]
Thank you. 

Probably it is not related, but can you please give a hint on why the tabbable div disappears bellow that zero-md. Maybe there is something with how the zero-md loads and thus the tabbable doesn't appear as it has inside zero-mds. It is interesting that this issue comes only for the first load on both Chrome and Firefox but if I refresh the page, slide away and back or open the developer tools, the tabbable div pops up...

**Comment by zerodevx** [comment]
Hmm I'm not really sure what you mean.. From your code it seems that your tab elements are a child of **only** your first slide, and not other slides? If that's the case then your tabs will only appear in the first slide and not the others.

**Comment by zaszlo** [comment]
Right, the tab should appear in the first slide (only) as the page loads but it doesn't, only after sliding back and forth or opening the devtools in the browser.

**Comment by zerodevx** [comment]
Swiper is calculating the initial height wrong. It's probably a timing issue. `<zero-md>` works asynchronously, so try adding a hook to tell Swiper to recalculate dimensions after `<zero-md>` is done with rendering. Something like:

```js
window.addEventListener('zero-md-rendered', function() {
  if (mySwiper) { mySwiper.update(); }
});

```
