### ISSUE TITLE
prism css

### ISSUE THREAD

**Issue by yetson0** [zerodevx/zero-md#62]
is there a way to remove Prism css formatting from the code block?
please advise,

**Comment by zerodevx** [comment]
If you don't provide a highlight stylesheet, then code blocks shouldn't appear formatted.

```html
<zero-md src="example.md">
  <template>
    <!-- Don't include highlight stylesheet -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/sindresorhus/github-markdown-css@4/github-markdown.min.css">
  </template>
</zero-md>
```

**Comment by yetson0** [comment]
excellent.

do you have any list off .css styles to use/modify which does your script use ? /hard to distinguish while your .js is minified
please advise,

**Comment by yetson0** [comment]
ok, plus my fault -- used:
<template data-merge="append">
insted of:
<template>
