### ISSUE TITLE
Not Rendering the math formula inside the markdown file !!

### ISSUE THREAD

**Issue by amatya-aditya** [zerodevx/zero-md#63]
While I can successfully parse other text from markdown on my website, I am finding it difficult to render the math formula written in the markdown file.  Is there a way to render those formulas with zero-md?

**Comment by zerodevx** [comment]
Have you tried the solution in this [issue](https://github.com/zerodevx/zero-md/issues/35)?

**Comment by amatya-aditya** [comment]
Thank you, It helped !!
