### ISSUE TITLE
Zero-md not displaying md file with a relative link

### ISSUE THREAD

**Issue by Instein98** [zerodevx/zero-md#64]
Firstly, thanks for your effort on this awesome project!

I'm trying the zero-md with a very simple example shown in README. But zero-md didn't display the md file. 

However, when I change the src link with a http link such as `https://raw.githubusercontent.com/zerodevx/zero-md/main/README.md`, it can work! I couldn't figure out why it can not display the md file with a relative link.

You can try [blog.zip](https://github.com/zerodevx/zero-md/files/7799665/blog.zip) if you want to reproduce.

--- 

My html look like:
```html
<!DOCTYPE html>
<html>
    <head>
        ...
        <!-- Import element definition -->
        <script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@2/dist/zero-md.min.js"></script>
        ...
      </head>
      <body>
        ...
        <!-- Profit! -->
        <zero-md src="README.md" ></zero-md>
        ...
      </body>
</html>

```
And my directory is like:
```
.
├── README.md
└── index.html
```

**Comment by zerodevx** [comment]
Your markdown file needs to be hosted. Browsers won't allow reading of local file system through javascript because security.

**Comment by zerodevx** [comment]
Marking this as closed - feel free to reopen if you need help.
