### ISSUE TITLE
how to add mermaid support?

### ISSUE THREAD

**Issue by CetinSert** [zerodevx/zero-md#65]
Following https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/, there might be greater use of mermaid overall. How can one go about adding official `mermaid` block support to `zero-md`?

**Comment by zerodevx** [comment]
Hey, thanks for your note. Given that Github now supports `mermaid` natively, I might add first-class support of this feature in a future release. In the meantime, something like this will work:

```html
<head>
  ...
  <!-- Load mermaid -->
  <script defer src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>    
  <script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@2/dist/zero-md.min.js"></script>
</head>

<body>
  <!-- Render zero-md in light dom -->
  <zero-md id="app" src="mermaid.md" no-shadow manual-render></zero-md>
  <script>
    app.addEventListener('zero-md-ready', async () => {
      // Create custom marked renderer
      const renderer = new marked.Renderer()
      renderer.code = function (code, lang) {
        return lang === 'mermaid'
          ? `<div class="mermaid">${code}</div>`
          : `<pre><code>${code}</code></pre>`
      }
      await app.render({ renderer })
      mermaid.init()
    })
  </script>
</body>
```

Here's a demo: https://plnkr.co/edit/Q64k8e498RfGDdlC

**Comment by simboonlong** [comment]
amazing library, looking forward to this feature

**Comment by mmoehrlein** [comment]
This was exactly what I was looking for! Awesome project, thanks a lot :)

**Comment by CetinSert** [comment]
@zerodevx – [the approach suggested above](https://github.com/zerodevx/zero-md/issues/65#issuecomment-1040237086) breaks encapsulation.

`<zero-md>` is the only web component that behaves like the HTML standard elements in that it does not gain attributes on getting connected to a document or leaks in other weird ways.

## Demo of how good `<zero-md>` is

The demo linked below uses **SyncHTML**.io – the next-gen playground that we are building!

---

See what we mean with the following steps:

1. Go to [`md.sy.ht?`](//md.sy.ht?) 👈🏻
2. Press <kbd>↑</kbd>/<kbd>↓</kbd> keys
3. Notice the video does not restart on edit.
This is all because you are doing custom elements right™ ❤️!

---

**SyncHTML**.io – the next-gen, no-reload, real-time web playground with instant two-way input ⇄ output sync.
([try](//sy.ht), [learn more](//synchtml.io))

**Comment by CetinSert** [comment]
---

<h2 id=sl> SyncHTML ❤️ <code>&lt;zero-md&gt;</code> </h2>

Dear @zerodevx,


We are in the process of implementing edge storage and deployment with sync versioning!

We have dedicated the short domain [**`md.sy.ht`**](//md.sy.ht) to the latest stable version of **`<zero-md>`**!
It is the shortest domain you can get that serves as an **editable** quick starting point! See below ↙️!

**In the address bar of your browser:**
| type | get |
| :- | :- |
| [`md.sy.ht?`](//md.sy.ht/?) | editor |
| [`md.sy.ht`](//md.sy.ht) | output |

All you need is a single `?` to edit your edge-deployed syncs!
Just hit <kbd>Ctrl</kbd>+<kbd>S</kbd> to update it in 275+ cities around the world!

(**Sync Deploy** restricts saves/updates to [Elefunc, Inc.](//efn.kr/tw) during the implementation phase.)

Best Regards,
@CetinSert

**Comment by zerodevx** [comment]
@CetinSert

> The demo linked below uses SyncHTML.io. (I am building it.)

 Wow! That's a cool project - looks really good!

> the approach suggested above breaks encapsulation.

Unfortunately, yes, mainly because of how `mermaid` works. For now, the markdown *must* be rendered into light dom - until first-class support is eventually added into `zero-md` (soon!). 😞

**Comment by zerodevx** [comment]
First class support for mermaid diagrams (into the shadow dom no less) is now available in [V3](https://github.com/highlightjs/highlight.js), so do check it out!
