### ISSUE TITLE
Throws a Server Error saying ReferenceError: HTMLElement is not defined

### ISSUE THREAD

**Issue by arlbibek** [zerodevx/zero-md#66]
# Throws a Server Error saying ReferenceError: HTMLElement is not defined

Hi, I am trying to integrate this project [zero-md](https://github.com/zerodevx/zero-md) into a [Next.js](https://nextjs.org/) project (i.e [bibeka.com.np](https://github.com/arlbibek/bibeka.com.np)) in order to embed a Markdown file within a html page, but for some reasons the app throws an **Server Error** saying `ReferenceError: HTMLElement is not defined`

## Here's what I've done/tried

File: `markdown.js`

```jsx
// Import the element definition
import ZeroMd from "zero-md";

// Register the custom element
customElements.define("zero-md", ZeroMd);

// Render anywhere
app.render(`<zero-md src=${src}></zero-md>`, target);
```

and

```jsx
import ZeroMd from "zero-md";

export default function Markdown() {
  return (
    <ZeroMd src="https://github.com/zerodevx/zero-md/blob/main/README.md"></ZeroMd>
  );
}
```

and

```jsx
import ZeroMd from "zero-md";

export default function Markdown() {
  customElements.define("zero-md", ZeroMd);
  return (
    <zero-md src="https://github.com/zerodevx/zero-md/blob/main/README.md"></zero-md>
  );
}
```

all of this throws the same error

## Error displayed

```text
Server Error

ReferenceError: HTMLElement is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:/C:/Users/bibek/arlbibek/bibeka.com.np/node_modules/zero-md/src/index.js (1:29)
ModuleJob.run
node:internal/modules/esm/module_job (195:25)
async ESMLoader.import
node:internal/modules/esm/loader (337:24)
async importModuleDynamicallyWrapper
node:internal/vm/module (437:15)
```

> Not sure if this is an issue or I'm missing something here. 🤔
> Please help.

**Comment by zerodevx** [comment]
That's probably due to [SSR](https://nextjs.org/docs/basic-features/pages#server-side-rendering) (doesn't play nicely with web components). You can try disabling it, or load `zero-md` using `<script>` tags, or try importing `zero-md` dynamically.

**Comment by zerodevx** [comment]
Marking this issue as closed.
