### ISSUE TITLE
Support for math equations

### ISSUE THREAD

**Issue by JaPatGitHub** [zerodevx/zero-md#69]
GitHub recently [announced](https://github.blog/2022-05-19-math-support-in-markdown/) support for math in TeX & LaTeX syntax. Is there a way the same can be supported by zero-md?

**Comment by zerodevx** [comment]
There's a recipe to render math with `MathJax`: https://zerodevx.github.io/zero-md/recipes/

**Comment by JaPatGitHub** [comment]
Will the same method work if I use zero md and mathjax as node module?

**Comment by zerodevx** [comment]
Hmm, I don't see why not.

**Comment by JaPatGitHub** [comment]
Thank you @zerodevx
