### ISSUE TITLE
Custom language in code blocks

### ISSUE THREAD

**Issue by NotLe0n** [zerodevx/zero-md#70]
Is it possible to add your own language syntax to code blocks? So for example I have the language "`ddp`" and I make a code block like this:

\```ddp
x ist 0.  [ x = 0; ]
\```

It should generate something like this:
```html
<pre class="language-ddp" tabindex="0">
  <code class="language-ddp">
    "x "
    <span class="token operator">ist </span>
    <span class="token number">0</span>
    <span class="token punctuation">.</span>
    <span class="token comment">[ x = 0; ]</span>
  </code>
</pre>
```

**Comment by zerodevx** [comment]
Yes. Does it not work?

**Comment by NotLe0n** [comment]
Well not really. What ends up getting generated is this:
```html
<pre class="language-ddp" tabindex="0">
  <code class="language-ddp">
    x ist 0. [ x = 0; ]
  </code>
</pre>
```
Since "ddp" is a esoteric language that isn't on [the list of supported languages](https://prismjs.com/#supported-languages), it doesn't know that "ist" is a operator, or that text surrounded by brackets are comments.

After looking through the Prism.js website some more, I found this article: https://prismjs.com/extending.html#language-definitions
which might be what I'm looking for.

**Comment by zerodevx** [comment]
Oh yes, so syntax highlighting is performed by Prism, and if it's not natively supported, then you're on the right track to extend it with your custom language definition. Don't think that's a trivial project though. =/

For supported languages, just the triple-backticks with the language shortcode should suffice.

**Comment by NotLe0n** [comment]
It was actually quite easy:
```js
document.addEventListener("DOMContentLoaded", () => {
    const md = document.getElementById("md");
    md.addEventListener('zero-md-ready', () => {
        Prism.languages['ddp'] = {
          'operator': /ist/,
          'comment': /\[[^.]*\]/,
          [...]
        }
    });
});
```

Thanks, anyways!
