### ISSUE TITLE
HTML code block not working correctly

### ISSUE THREAD

**Issue by a-was** [zerodevx/zero-md#75]
I'm trying to display inline markdown with html code blocks inside for some of my documentation like this:

```html
<zero-md>
    <script type="text/markdown">
    some docs...

    ```html
    <script type="text/javascript" src="..."></script>
    ```

    </script>
</zero-md>
```

But inner closing script tag is working, I mean zero-md ends with it. I tried to escape this tag in many different ways, but I only end with not valid tag like `\<script\>` or `&lt;` displayed

Could this be handled in some way?

**Comment by zerodevx** [comment]
Make sure there's no indentation in your inline markdown.

````html
<zero-md>
    <script type="text/markdown">
some docs...

```html
<script type="text/javascript" src="..."></script>
```
    </script>
</zero-md>
````

**Comment by a-was** [comment]
Actually, I tried this at first, then added indentation. Both works the same (zero-md ends)

**Comment by zerodevx** [comment]
I don't think there's a workaround. The browser parser treats the first `</script>` closing tag it encounters as the end of script. Alternatively, load your markdown from an external file instead.

**Comment by a-was** [comment]
Okay, thanks for help
