### ISSUE TITLE
How to use zeroMd as module?

### ISSUE THREAD

**Issue by Graciasjr** [zerodevx/zero-md#77]
Hello zero-dev , i have installed zero-md using cli but it's not easy for me to use it in framework despite Reading Docs😭

I imported { zeroMd}in my page.svelte and i don't know how to use it as components. 
Help me please

**Comment by zerodevx** [comment]
Hey, sorry for the late response. `zero-md` is a web component so generally I'd recommend just loading the script from CDN using a `<script>` tag. Then you can just use `<zero-md>` element anywhere in your Svelte app without caring about imports etc.

**Comment by Graciasjr** [comment]
Thank you for your reply even though it is so late. Yes I got it after many tries. Thank you for your reply.

**Comment by zerodevx** [comment]
Sorry! I was swarmed... 😫 

Will close this for now, feel free to raise another issue if you need help.
