### ISSUE TITLE
Cyrillic anchor links doesn't works

### ISSUE THREAD

**Issue by ulbwa** [zerodevx/zero-md#78]
If you use the headers in Cyrillic, the anchor links written to them will not scroll the page to the desired h tag.

```
[latin anchor link works](#latin-header)

[cyrillic anchor link doesn't works](#кириллический-заголовок)

# Latin header

some text
 
# Кириллический заголовок

some text
```

**Comment by zerodevx** [comment]
Thanks for the report - I should really look into supporting non-latin characters.

**Comment by zerodevx** [comment]
Marking this as an enhancement because slugification is in the remit of `markedjs`: https://marked.js.org/using_pro#renderer

Might add first class support in a future release.
