### ISSUE TITLE
Link clicks do not open in new tab

### ISSUE THREAD

**Issue by ernsheong** [zerodevx/zero-md#8]
Trying to CMD + click on link within element does not open in new tab, takes over current tab.

I see that you are hijacking links to make the scrolling work.

**Comment by zerodevx** [comment]
Ahh yes.. Anchor links (the automatic jumping to a section by its ID) is a browser feature that unfortunately doesn't work in Shadow DOMs, so we have to patch that feature in. I'll add support for CMD+clicks in a moment.

**Comment by zerodevx** [comment]
I've just released a minor update v1.2.1 that should fix this.

**Comment by ernsheong** [comment]
Thanks for the quick response. There is still a bug: https://github.com/zerodevx/zero-md/pull/9#pullrequestreview-198898710

**Comment by zerodevx** [comment]
Thanks, looking at it now.
