### ISSUE TITLE
nginx example

### ISSUE THREAD

**Issue by ssipos90** [zerodevx/zero-md#80]
Hi,

Cool project!

I've set up an nginx docker container that serves an index.html as per the docs. I've also mounted my obsidian notes and it works fine rendering the initial md file, but whenever I click a link, the browser downloads the file from my server instead of rendering it. Do I have to do something more besides including the script tag and using the component?

```html
 <script
      type="module"
      src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@2/dist/zero-md.min.js"
    ></script>
```
and 
```html
 <zero-md src="Notes/0000.md"></zero-md>
```

Thank you!

**Comment by zerodevx** [comment]
Hey sorry for the late reply. I'm assuming the link is in the contents of your markdown. What does it link to? Behaviour is exactly like a normal webpage - if the anchor links to another webpage, that webpage will be visited; if it links to a `.md` file for example, the browser downloads it per usual.

**Comment by ssipos90** [comment]
Oh, ok, so that's what I was getting (md downloads).

I thought the library allowed me to navigate md links in my notes and I didn't configure it properly somehow.
