### ISSUE TITLE
Does zero-md support admonition marked plug-in?

### ISSUE THREAD

**Issue by RootofalleviI** [zerodevx/zero-md#90]
https://www.npmjs.com/package/marked-admonition-extension

**Comment by zerodevx** [comment]
The thing is `markedjs` extension system is a `marked` v5 feature, but `zero-md` is still using v4 at the moment. For custom styling, I'll definitely recommend following a pattern like https://github.com/zerodevx/zero-md/issues/91#issuecomment-1636720087 instead.

**Comment by RootofalleviI** [comment]
Thanks!

**Comment by RootofalleviI** [comment]
Is there any plan to upgrade Marked.js to version 5? Based on https://github.com/markedjs/marked/releases, I guess the changes are 
- support extension system
- replace deprecated options (if passed in) with corresponding extensions

Thanks!

**Comment by zerodevx** [comment]
Yes, indeed there are. I do have a tonne of upgrades to add into the next major, features like:

- first class support for Mermaid and MathJax
- fully migrate to ESM
- drop support for legacy browsers
- basically the little stuff to bring `zero-md` to feature-parity with Github-flavoured markdown

I'll work on it once I get some time!

**Comment by RootofalleviI** [comment]
Thanks a lot!

**Comment by RootofalleviI** [comment]
Hi there!

I hope you're doing great. Just checking in to see how things are going with the next version of zero-md. I'm pretty excited about the idea of using markedjs extensions in it. Thanks a bunch for all the hard work!

**Comment by zerodevx** [comment]
Hey there! Doing well, just busy! 😫  Just reverting the previous title for posterity - so other folks who may have the same question finds this thread. Moved your post to #103 instead.
