### ISSUE TITLE
Parse/Render text within HTML tags

### ISSUE THREAD

**Issue by RootofalleviI** [zerodevx/zero-md#91]
It seems that the text inside HTML tags are not treated as markdown and not parsed/rendered:
```
# H1

<div id="test">
**This should be bold**
</div>
```

Is there a way we could support that? I'm trying to create custom rules for markdown. One option is to use admonition but I haven't figured out how to add that. The second option is to change the markdown parser/tokenizer but that feels very complicated. The third option is to use HTML directly inside markdown source, so I'm wondering if the content inside HTML tags are treated as markdown at all. Thanks!

**Comment by zerodevx** [comment]
Hi @RootofalleviI, first of all thanks for your sponsorship, much appreciated. 🙏 

> It seems that the text inside HTML tags are not treated as markdown and not parsed/rendered:

I think this is standard markdown behaviour. If you just paste this:

```
<div id="test">
**This should be bold**
</div>
```

 into the comment box here it doesn't get parsed as well.

> The third option is to use HTML directly inside markdown source,

If you're looking to apply custom styles to parts of your markdown, definitely use this approach. For example:

```html
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@2/dist/zero-md.min.js"></script>
</head>
<body>
  <zero-md>
    <template data-merge="append">
      <style>
        .custom { border: 1px solid red; }
        .custom .title { background: rgba(0,0,0,0.3) }
      </style>
    </template>
    <script type="text/markdown">
# This is a heading

The quick brown fox jumps over the lazy dog.

<div class="custom">
  <div class="title">Info</div>
  <div class="detail">Here are the details</div>
</div>
    </script>
  </zero-md>
</body>```

**Comment by RootofalleviI** [comment]
I see, this means I want to write HTML and CSS directly inside the markdown if I want anything custom. Thanks a lot!
