### ISSUE TITLE
prism.js seems to not recognize C++?

### ISSUE THREAD

**Issue by RootofalleviI** [zerodevx/zero-md#92]
![image](https://github.com/zerodevx/zero-md/assets/22670473/9a9699f2-6ae4-4509-b9ff-dca4dad7bfeb)

```python
def f():
  print("Hello World!")
```

```java
public static void main(String[] args) {
  System.out.println("Hello World!");
}
```

```typescript
console.log("Hello World!");
```

```c++
int main() {
    std::cout << "Hello World!";
    return 0;
}
```

```c
int main() {
   printf("Hello, World!");
   return 0;
}
```

I'm using: `<link href="https://cdn.jsdelivr.net/gh/PrismJS/prism@1/themes/prism.min.css" rel="stylesheet">`

**Comment by zerodevx** [comment]
It looks styled here: https://jsbin.com/pohedahexi/1/edit?html,output

**Comment by RootofalleviI** [comment]
Hmm it seems that if I remove "c++" after \`\`\` then the renderer automatically detects it as c++. Interesting.

**Comment by zerodevx** [comment]
C++ code blocks should probably be hinted with `cpp`.
