### ISSUE TITLE
Mermaid Support Broken Since Version 2.5.1

### ISSUE THREAD

**Issue by gillesdb** [zerodevx/zero-md#94]
Since version 2.5.1, the Mermaid support has been broken. This issue appears to be related to a change in the code where a JSON.stringify operation is performed on the opts object. This change results in an 'index.js:328 Uncaught (in promise) TypeError: Converting circular structure to JSON' error when using Mermaid diagrams.
![image](https://github.com/zerodevx/zero-md/assets/6920693/cf56af0b-7881-45ea-b041-b17325e72217)

The Plunker demo with mermaid has the same issue: https://plnkr.co/edit/Q64k8e498RfGDdlC?preview
We have currently applied a prefix to version 2.5.0 as a temporary fix to resolve our issue.

Thank you for your attention to this matter.

**Comment by zerodevx** [comment]
Thanks for your bug report - I'll fix it.

**Comment by zerodevx** [comment]
This is fixed in `v2.5.3` - thanks again, great catch!

**Comment by gillesdb** [comment]
Thanks for the quick fix; the issue has been successfully resolved!
