### ISSUE TITLE
Display table of content TOC

### ISSUE THREAD

**Issue by damascene** [zerodevx/zero-md#96]
Thank you for this useful library. 

Is there a simple way to display table of content in the page?

I see two closed PR related to TOC

https://github.com/zerodevx/zero-md/pull/27
https://github.com/zerodevx/zero-md/pull/28

**Comment by alifeee** [comment]
If you use VSCode, you can use [Markdown All In One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) to create an automatically-updating table of contents within the markdown file.

**Comment by damascene** [comment]
> If you use VSCode
Thank you for responding. I don't, seems the plugin you are refereeing to is written in Typescript. Would it be possible to port code from it?

**Comment by alifeee** [comment]
> Thank you for responding. I don't, seems the plugin you are refereeing to is written in Typescript. Would it be possible to port code from it?

I'm not sure, but it looks like the logic is in [toc.ts](https://github.com/yzhang-gh/vscode-markdown/blob/master/src/toc.ts)

You could also create a file to manually make a TOC. For example, I did this [here](https://github.com/alifeee/blog/blob/main/utilities.py/toc_markdown.py) with Python (this solution is in no way exhaustive, it was just a personal thing).

**Comment by zerodevx** [comment]
> Thank you for this useful library.
> 
> Is there a simple way to display table of content in the page?
> 
> I see two closed PR related to TOC
> 
> #27 #28

These PRs are made in error.

However, generating TOCs are probably not in the remit of this package. Closing for now, feel free to repoen.
