### ISSUE TITLE
Markdown not translated into HTML

### ISSUE THREAD

**Issue by epatrick** [zerodevx/zero-md#98]
Curious: given [this jsfiddle example](https://jsfiddle.net/epatrick/hesxjmpn/) (copied from the [Basic Usage](https://zerodevx.github.io/zero-md/basic-usage/)), I expected to see the markdown translated into HTML.

I suspect I missed something very basic?

Thanks in advance!

**Comment by zerodevx** [comment]
It's a whitespace issue. Per markdown specs, new line starting with 4 spaces represents a code block. I guess the example should remove it.

**Comment by epatrick** [comment]
Doh - simple indeed. Thanks!
